version: '3.8'

services:
  transcoder-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simpenan-worker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./temp_worker:/app/temp_worker
